#see https://github.com/ChrisCarini/intellij-platform-plugin-verifier-action
name: Compatibility
on: [ push, pull_request ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Build the plugin using Gradle
        run: ./gradlew buildPlugin
      - uses: ChrisCarini/intellij-platform-plugin-verifier-action@v1.0.3
        with:
          #TODO use ideaIC:2023.1 and ideaIU:2023.1 on FCS
          ide-versions: |
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT
